### ISSUE TITLE
Can't get plugin to work 

### ISSUE THREAD

**Issue by juliannehalversen** [lucky3491/cordova-plugin-wkwebview-inject-cookie#1]
This plugin does exactly what I need but I can't get it to work.
 I added the plugin: 
```ionic cordova plugin add cordova-plugin-wkwebview-inject-cookie```

Here is my **package.json:**
```
 "cordova": {
    "plugins": {
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-keychain-touch-id": {},
      "cordova-plugin-privacyscreen": {},
      "cordova-plugin-wkwebview-inject-cookie": {}
    },
    "platforms": [
      "ios",
      "android"
    ]
  }
}
```

Here is the plugin in my **config.xml:**
``<plugin name="cordova-plugin-wkwebview-inject-cookie" spec="https://github.com/lucky3491/cordova-plugin-wkwebview-inject-cookie" />``

And here is my **app.component.ts** where I try to inject a dummy cookie: 
```
declare var wkWebView: any;

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  constructor(
    private platform: Platform,
    private splashScreen: SplashScreen,
    private statusBar: StatusBar,
    private authService: AuthenticationService,
    public router: Router,
    public loadingController: LoadingController,
  ) {
    this.initializeApp();
  }

  initializeApp() {
    this.platform.ready().then(() => {
      this.statusBar.styleDefault();
      this.splashScreen.hide();

      if (this.platform.is('ios')) {
        const cookiesArray = [{
          domain: 'abc.xyz',
          name: 'cookie name',
          path: '/',
          value: 'cookie string'
        }, {} ];

        wkWebView.injectCookie(cookiesArray);
      }
   )}
  }
}
```

I have been working on this and am not sure where I'm going wrong. Any help would be greatly appreciated!

**Comment by kbrin423** [comment]
Hi! Same problem for me here :(

**Comment by juliannehalversen** [comment]
@kbrin423 I got mine to work. Below is the working code: 

In my config.xml I added the inject cookie: 
```
<plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="cordova-plugin-statusbar" spec="2.4.2" />
    <plugin name="cordova-plugin-device" spec="2.0.2" />
    <plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
    <plugin name="cordova-plugin-ionic-webview" spec="^4.0.0" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="^2.0.5" />
    <plugin name="cordova-plugin-privacyscreen" spec="0.4.0" />
    <plugin name="cordova-plugin-wkwebview-inject-cookie" spec="1.1.4" />
```

In my package.json I have added it to my cordova plugins object: 
```
"cordova": {
    "plugins": {
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-keychain-touch-id": {},
      "cordova-plugin-privacyscreen": {},
      "cordova-plugin-wkwebview-cookie-sync": {},
      "cordova-plugin-wkwebview-inject-cookie": {},
}
```

In my app.component.ts I declare wkWebView: 
```
declare var wkWebView: any;

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['./app.component.scss'],
})
```
and then when the app is initializing I check if the platform is IOS. If it is then I will manually inject a cookie: 

```
 initializeApp() {
    this.platform.ready().then(() => {
      this.statusBar.styleDefault();
      this.splashScreen.hide();

      // This syncs the cookies on IOS devices when the app initializes.
      // This ensures that the login response cookie will be sent with all subsequent requests.
      if (this.platform.is('ios')) {
        wkWebView.injectCookie('YOUR API ENDPOINT HERE');
      }
```

This was a little tricky for me and there were any detailed instructions on how to set it up. Give this a try and let me know if you are still having issues.

**Comment by kbrin423** [comment]
I got mine to work too! thx 👍

**Comment by AlekseyPim** [comment]
@juliannehalversen What wkWebview plugin did you used?

**Comment by juliannehalversen** [comment]
@AlekseyPim As you can see in my config I used cordova-plugin-ionic-webview and for the cookie issue I used the one from this repo

**Comment by hiperiumlw** [comment]
@juliannehalversen I have an issue with my Ionic app that affects setting session cookies. When I do login in my app, my server API sends me an Header with "Set-Cookie" param. On Android, everything works fine...but...on iOs, I can't manage to save that cookie received from the Header Response. Could you please tell me if this method will work for me? Thanks in advance.

**Comment by lucky3491** [comment]
> @juliannehalversen I have an issue with my Ionic app that affects setting session cookies. When I do login in my app, my server API sends me an Header with "Set-Cookie" param. On Android, everything works fine...but...on iOs, I can't manage to save that cookie received from the Header Response. Could you please tell me if this method will work for me? Thanks in advance.

@juliannehalversen you have to send cookies to different header param because that one is restricted to use

**Comment by hiperiumlw** [comment]
> > @juliannehalversen I have an issue with my Ionic app that affects setting session cookies. When I do login in my app, my server API sends me an Header with "Set-Cookie" param. On Android, everything works fine...but...on iOs, I can't manage to save that cookie received from the Header Response. Could you please tell me if this method will work for me? Thanks in advance.
> 
> @juliannehalversen you have to send cookies to different header param because that one is restricted to use

@lucky3491 
What do you mean exactly? I'm using Angular & Ionic, and when I make the Login request, i send the following
`const headers = new HttpHeaders({
            'Content-Type': 'application/json'
        });
        const options = ({
            headers,
            withCredentials: true
        });`

Like i said, on Android everything works fine, but on iOs, my cookie isn't set.
This plugin really can't help me with this?

Thanks.

**Comment by AlekseyPimenov** [comment]
@hiperiumlw Foe me the same problem with 'Set-Cookie', this plugin not help with that, it should fix another issue...
Also looking solution for 'Set-Cookie'

**Comment by lucky3491** [comment]
@hiperiumlw when you received cookies from your server. You have to send that cookies array to this plugin but from server normally you get cookies in set-cookies param that is restricted to use so you have to change your response header name for cookies

**Comment by hiperiumlw** [comment]
> @hiperiumlw when you received cookies from your server. You have to send that cookies array to this plugin but from server normally you get cookies in set-cookies param that is restricted to use so you have to change your response header name for cookies

@lucky3491 So, what you suggest is to receive another Cookie Response Header like "Cookie New Name" with the value and send it to the plugin? After that, all following requests will sent the Cookie Header Request Param?

**Comment by lucky3491** [comment]
@hiperiumlw Yes i am using this way and its working for me

**Comment by Carlosps** [comment]
Thank you guys for your help.

Make sure when calling setCookie directly you add the '/', otherwise it won't work properly.

`wkWebView.setCookie('url.com' + '/', 'cookieName', 'cookieValue');`

setCookie expects (url, name, value, successCallback, errorCallback) as parameters.

**Comment by hiperiumlw** [comment]
> Thank you guys for your help.
> 
> Make sure when calling setCookie you add the '/', otherwise it won't work properly.
> 
> `wkWebView.setCookie(url + '/', 'cookieName', 'cookieValue');`

But...Are you using the wkWebView.injectCookie('YOUR API ENDPOINT HERE'); ?

Why do you use wkWebView.setCookie instead of injectCookie?

**Comment by Carlosps** [comment]
@hiperiumlw No, I am not using the injectCookie.

I was having some issues with injectCookie.

`injectCookie: function (url, successCallback, errorCallback) {
    this.setCookie(url, "foo", "bar", successCallback, errorCallback);
  }`

Why not use setCookie?

**Comment by hiperiumlw** [comment]
> @hiperiumlw No, I am not using the injectCookie.
> Why not use setCookie?

But....you are using this plugin, right?

**Comment by Carlosps** [comment]
Yes, as I said in my first comment.

**Comment by hiperiumlw** [comment]
> Yes, as I said in my first comment.

Is it working with the simulator or only with real devices...? Only asking :)

**Comment by Carlosps** [comment]
> Is it working with the simulator or only with real devices...? Only asking :)

I haven't tested with the simulator yet, only using the device.

**Comment by hiperiumlw** [comment]
> > Is it working with the simulator or only with real devices...? Only asking :)
> 
> I haven't tested with the simulator yet, only using the device.

And which versions of iOs have you tried? Thanks!

**Comment by Carlosps** [comment]
> And which versions of iOs have you tried? Thanks!

iOS software version: 13.5.1

**Comment by julitroalves** [comment]
@juliannehalversen thanks a lot for your clarification about how to use this plugin with ionic.
Another tip for all install plugin with link of this github plugin because there is another plugin with the same name, and when you run it the another plugin was installed.
Please run: `cordova plugin add https://github.com/lucky3491/cordova-plugin-wkwebview-inject-cookie`

**Comment by sachinkumaram-veoci** [comment]
> @hiperiumlw when you received cookies from your server. You have to send that cookies array to this plugin but from server normally you get cookies in set-cookies param that is restricted to use so you have to change your response header name for cookies

Is it working with iOS 14.0? mine is not working, how to debug it?

**Comment by hiperiumlw** [comment]
> > @hiperiumlw when you received cookies from your server. You have to send that cookies array to this plugin but from server normally you get cookies in set-cookies param that is restricted to use so you have to change your response header name for cookies
> 
> Is it working with iOS 14.0? mine is not working, how to debug it?

Have just tried with iOS 14 and it doesn't work...
Any news about iOS 14 versions? Anyone?

**Comment by juliannehalversen** [comment]
> @juliannehalversen thanks a lot for your clarification about how to use this plugin with ionic.
> Another tip for all install plugin with link of this github plugin because there is another plugin with the same name, and when you run it the another plugin was installed.
> Please run: `cordova plugin add https://github.com/lucky3491/cordova-plugin-wkwebview-inject-cookie`

Yes, thanks for clarifying. I had run into that issue as well which caused me tons of confusion

**Comment by razam217** [comment]
Its not working for me even on iOS 12.4.6, iPhone 5s :(

**Comment by lucky3491** [comment]
@hiperiumlw it is working for me in ios 14 not event change anything in this

**Comment by siphiwe** [comment]
> @kbrin423 I got mine to work. Below is the working code:
> 
> In my config.xml I added the inject cookie:
> 
> ```
> <plugin name="cordova-plugin-whitelist" spec="1.3.3" />
>     <plugin name="cordova-plugin-statusbar" spec="2.4.2" />
>     <plugin name="cordova-plugin-device" spec="2.0.2" />
>     <plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
>     <plugin name="cordova-plugin-ionic-webview" spec="^4.0.0" />
>     <plugin name="cordova-plugin-ionic-keyboard" spec="^2.0.5" />
>     <plugin name="cordova-plugin-privacyscreen" spec="0.4.0" />
>     <plugin name="cordova-plugin-wkwebview-inject-cookie" spec="1.1.4" />
> ```
> 
> In my package.json I have added it to my cordova plugins object:
> 
> ```
> "cordova": {
>     "plugins": {
>       "cordova-plugin-inappbrowser": {},
>       "cordova-plugin-whitelist": {},
>       "cordova-plugin-statusbar": {},
>       "cordova-plugin-device": {},
>       "cordova-plugin-splashscreen": {},
>       "cordova-plugin-ionic-webview": {},
>       "cordova-plugin-ionic-keyboard": {},
>       "cordova-plugin-keychain-touch-id": {},
>       "cordova-plugin-privacyscreen": {},
>       "cordova-plugin-wkwebview-cookie-sync": {},
>       "cordova-plugin-wkwebview-inject-cookie": {},
> }
> ```
> 
> In my app.component.ts I declare wkWebView:
> 
> ```
> declare var wkWebView: any;
> 
> @Component({
>   selector: 'app-root',
>   templateUrl: 'app.component.html',
>   styleUrls: ['./app.component.scss'],
> })
> ```
> 
> and then when the app is initializing I check if the platform is IOS. If it is then I will manually inject a cookie:
> 
> ```
>  initializeApp() {
>     this.platform.ready().then(() => {
>       this.statusBar.styleDefault();
>       this.splashScreen.hide();
> 
>       // This syncs the cookies on IOS devices when the app initializes.
>       // This ensures that the login response cookie will be sent with all subsequent requests.
>       if (this.platform.is('ios')) {
>         wkWebView.injectCookie('YOUR API ENDPOINT HERE');
>       }
> ```
> 
> This was a little tricky for me and there were any detailed instructions on how to set it up. Give this a try and let me know if you are still having issues.

Hi there,
Thanks for confirming that there's hope. I've done what you describe but not winning. Do you know what the variable wkWebView is referencing? Without instantiating anything, it calls an injectCookie() method. Not sure where to start debugging my issue, really. Any pointers would be appreciated. I'm using ionic 3.9.9 with cordova-ios 5.1.1. My webview is cordova-plugin-wkwebview-engine 1.2.1. The ionic webview couldn't even successfully make API calls, for some reason I couldn't fathom. Any assistance would be appreciated

**Comment by newuser44** [comment]
Yeah I tried above (I had to run the add command to get the plugin installed).  

My bad, I can't even get the plugin installed. 

Failed to install 'cordova-plugin-wkwebview-inject-cookie': Error: Unable to load Platform API from /Users/w437982/work/WebKit/gf-efs-mobile-mobileapps/pay-control/platforms/ios/cordova/Api.js:
Cannot find module 'unorm'

**Comment by newuser44** [comment]
> @hiperiumlw Foe me the same problem with 'Set-Cookie', this plugin not help with that, it should fix another issue...
> Also looking solution for 'Set-Cookie'

Any fix?

**Comment by kbrin423** [comment]
Hi! Now i installed this plugin :https://github.com/oracle/cordova-plugin-wkwebview-file-xhr 💯

**Comment by newuser44** [comment]
> Hi! Now i installed this plugin :https://github.com/oracle/cordova-plugin-wkwebview-file-xhr 💯

Thanks.   How do you use this to do cookies?

**Comment by aronAtWex** [comment]
> @hiperiumlw it is working for me in ios 14 not event change anything in this

How did you get this working for ios 14.  
I had everything working with ios 13.5  pushed up for apple and they rejected it.  
I'm trying in a emulator with ios 14 and it does not work.  
Never got a clear answer/idea what to put in for the domain.  Ionic/cordova apps have their own domain.  
localhost was working fine with 13.5.  Maybe path is more important.  
Now I'm stuck.    This plugin should be closed if it does not work with ios 14.  Apple will reject it.

**Comment by luizchaves97** [comment]
@newuser44 Do you find how to use this plugin to get cookies?

**Comment by aronAtWex** [comment]
> @newuser44 Do you find how to use this plugin to get cookies?

All the plugs I tried, including this one, I could never get working.  Seems like a good number of them are not supported or have been been updated with the ios 14 updates.  

What I did to get this working was.  
Removing any plugs I had to fix cookies for WKWebView.  

Storing cookies locally -- had to write some new code to use local storage instead of cookies.  So far its working but I hear ios can pretty much clear memory when ever it wants to.   

For login cookies  in the config.xml I added a hostname tag under the ios section.  

```
<platform name="ios">
        <preference name="Hostname" value="dev.test.com" />
        <preference name="WKWebViewOnly" value="true" />
        <feature name="CDVWKWebViewEngine">
            <param name="ios-package" value="CDVWKWebViewEngine" />
        </feature>
```
This solved the problem of CORS and cookies being stored because the ios app thinks it making the call from the same server.  ios app is dev.test.com  and I'm making my api calls to dev.test.com.   

Does have to be exact.  test.com  won't work.  (Unless that is the site).  

I already had a webpack.config.js script to rewrite some values in config.xml depending on which environment I was building for.  I hooked into that and other environment values to rewrite this Hostname line depending on the build.  

So far things have worked great.

**Comment by newuser44** [comment]
> @newuser44 Do you find how to use this plugin to get cookies?

All the plugs I tried, including this one, I could never get working. Seems like a good number of them are not supported or have not been updated with the ios 14 updates.

What I did to get this working was.
Removing any plugs I had to fix cookies for WKWebView.

Storing cookies locally -- had to write some new code to use local storage instead of cookies. So far its working but I hear ios can pretty much clear memory whenever it wants to.

For login cookies in the config.xml I added a hostname tag under the ios section.

<platform name="ios">
        <preference name="Hostname" value="dev.test.com" />
        <preference name="WKWebViewOnly" value="true" />
        <feature name="CDVWKWebViewEngine">
            <param name="ios-package" value="CDVWKWebViewEngine" />
        </feature>
This solved the problem of CORS and cookies being stored because the ios app thinks it making the call from the same server. ios app is dev.test.com and I'm making my api calls to dev.test.com.

Does have to be exact. test.com won't work. (Unless that is the site).

I already had a webpack.config.js script to rewrite some values in config.xml depending on which environment I was building for. I hooked into that and other environment values to rewrite this Hostname line depending on the build.

So far things have worked great.
